### ISSUE TITLE
Failure when ClientSecurityContext used without credentials

### ISSUE THREAD

**Issue by eltoder** [jborean93/sspilib#11]
ClientSecurityContext's `credential` parameter is optional. The docstring says that it defaults to the current user context if not set. However, when I don't pass it I get an exception:
```python
import sspilib
ctx = sspilib.ClientSecurityContext('s/h')
ctx.step(None)
```
generates
```
OSError: [WinError -2146893055] The handle specified is invalid
```
If I pass default UserCredential, step works fine:
```python
ctx = sspilib.ClientSecurityContext('s/h', credential=sspilib.UserCredential())
ctx.step(None)
```

**Comment by jborean93** [comment]
I think this is my fault, the underlying API [InitializeSecurityContext](https://learn.microsoft.com/en-us/windows/win32/api/sspi/nf-sspi-initializesecuritycontextw) has marked this argument as optional `[in, optional]      PCredHandle      phCredential,` but I think that might only be true for subsequent calls to the function after the credentials were already supplied on the first one.

This is somewhat confirmed by [SpInitLsaModeContextFn](https://learn.microsoft.com/en-us/windows/win32/api/ntsecpkg/nc-ntsecpkg-spinitlsamodecontextfn) which is used by SSPI providers to implement this function

> Optional. Handle to the [credentials](https://learn.microsoft.com/en-us/windows/desktop/SecGloss/c-gly) to use for the context. CredentialHandle can be NULL if the ContextHandle parameter is not NULL.

This will have to be updated to become not Optional but I'll need to think about the best way to do this without potentially breaking people who call the security context object with positional args.

**Comment by jborean93** [comment]
Thanks for picking this up, I've opened https://github.com/jborean93/sspilib/pull/13 which updates the docs and slightly rearranges the positional arguments for the SecurityContext objects.
