### ISSUE TITLE
Package name collides with win32 sspi module

### ISSUE THREAD

**Issue by johannesloibl** [jborean93/sspilib#5]
The migration of SSPI from [pyspnego](https://github.com/jborean93/pyspnego) to this new library leads to a collision with the sspi.py module from the win32 package ("...\Lib\site-packages\win32\lib\sspi.py").

So when i import requests_negotiate_sspi, it will import your package instead of the sspi module and access `sspi.ClientAuth`,  which fails.

Maybe rename the package? :)

**Comment by jborean93** [comment]
Hmm I checked as many packages as I could to see if they used `sspi` but missed this. I was not aware that python loaders worked with something like the `lib` dir inside a package like this. I might have to yank the pyspnego version and push out a new one once this package is renamed. I was thinking `sspic` or `csspi` but open to suggestions.

**Comment by jborean93** [comment]
This has been renamed to [sspic](https://pypi.org/project/sspic/). The pyspnego release has been yanked and a new one will be forthcoming with the renamed dependency.

**Comment by johannesloibl** [comment]
Awesome, thanks :)
