### ISSUE TITLE
VirusTotal has found out a trojan "Trojan.Generic.hragh"

### ISSUE THREAD

**Issue by ax-va** [jborean93/sspilib#9]
Hi,

scanning sspilib with VirusTotal gives me a trojan "Trojan.Generic.hragh" in the single version of package found out by Jiangmin:
https://www.virustotal.com/gui/file/61c9067168cce962f7fead42c28804c3a39a164b9a7b660200b8cfe31e3af071

![image](https://github.com/jborean93/sspilib/assets/85578981/d556edc9-edfa-44c4-99ac-c37bf87119b2)

I hope this report will help.

Best regards,
Alex

**Comment by jborean93** [comment]
Not much I can do sorry. You can inspect the code to see that isn’t malicious and if you don’t trust the wheels shipped through PyPI you can build it straight from source.
